### ISSUE TITLE
An all_on_start option?

### ISSUE THREAD

**Issue by nathany** [jejacks0n/guard-teaspoon#25]
It would be nice to have an `all_on_start:  false` option like [guard-jasmine](https://github.com/netzpirat/guard-jasmine#spec-runner-options).

**Comment by FinnWoelm** [comment]
This is old, but for anyone looking for the answer in 2016, this has been added.

Simply add `all_on_start: false` to your Guardfile, so that it becomes

    guard :teaspoon, all_on_start: false do
       ....
    end

You can find more config options for guard-teaspoon in this file: https://github.com/jejacks0n/guard-teaspoon/blob/master/lib/guard/teaspoon.rb
